language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_script: 
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install -n
  - git --version
  - git config --global user.email "test@travis-ci.org"
  - git config --global user.name "Travis"
  - git --version
  - php app/console doctrine:database:create --env=test
  - php app/console version:install --env=test
  - php app/console doctrine:fixtures:load --no-interaction --env=test

script: phpunit -c app --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v
