language: php

services:
  - mysql

php:
  - 7.2

before_script:
  - cp app/app/config/parameters.yml.travis app/app/config/parameters.yml
  - cd app
  - composer install -n
  - git --version
  - git config --global user.email "test@travis-ci.org"
  - git config --global user.name "Travis"
  - git --version
  - php app/console doctrine:database:create --env=test
  - php app/console version:install --env=test
  - php app/console doctrine:fixtures:load --no-interaction --env=test

script: phpunit --coverage-clover build/logs/clover.xml -c app

after_script:
 - bin/coveralls -v
