services:
    version_control.git_command_base:
        abstract:  true
        calls:
            - [setSecurityContext, ["@security.token_storage"]]
            - [setProjectEnvironmentStorage, ["@version_control.project_environmnent_storage"]]
            - [setDispatcher, ["@event_dispatcher"]]
            
    version_control.git_log:
        class:  VersionContol\GitControlBundle\Utility\GitCommands\GitLogCommand
        parent: version_control.git_command_base
        
    version_control.git_sync:
        class:  VersionContol\GitControlBundle\Utility\GitCommands\GitSyncCommand
        parent: version_control.git_command_base
        
    version_control.git_branch:
        class:  VersionContol\GitControlBundle\Utility\GitCommands\GitBranchCommand
        parent: version_control.git_command_base
        
    version_control.git_status:
        class:  VersionContol\GitControlBundle\Utility\GitCommands\GitStatusCommand
        parent: version_control.git_command_base
    
    version_control.git_files:
        class:  VersionContol\GitControlBundle\Utility\GitCommands\GitFilesCommand
        parent: version_control.git_command_base