services:
    version_control.git_command_base:
        abstract:  true
        calls:
            - [setSecurityContext, ["@security.token_storage"]]
            - [setProjectEnvironmentStorage, ["@version_control.project_environmnent_storage"]]
            
    version_control.git_log:
        class:  VersionContol\GitControlBundle\Utility\GitCommands\GitLogCommand
        parent: version_control.git_command_base