version_contol_git_control:
    resource: "@VersionContolGitControlBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#hwi_oauth_security:
#    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix: /apilogin

#hwi_oauth_connect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
#    prefix: /apilogin
    
#hwi_oauth_redirect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /apilogin

    
github_login:
    path: /login/check-github
    
version_contol_github_issue_control:
    resource: "@VersionControlGithubIssueBundle/Controller/"
    type:     annotation
    prefix:   /
    
version_contol_gitlab_issue_control:
    resource: "@VersionControlGitlabIssueBundle/Controller/"
    type:     annotation
    prefix:   /
