services:
           
    lrotherfield.form.type.hidden_entity:
        class: Lrotherfield\Component\Form\Type\HiddenEntityType
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type, alias: hidden_entity }
            
    salavert.twig.time_ago:
        class: Salavert\Twig\Extension\TimeAgoExtension
        arguments: ['@translator']
        tags:
        - { name: twig.extension }
           
     
    fos_user.doctrine_registry:
        alias: doctrine
