services:
    version_control.git_command:
        class: VersionContol\GitControlBundle\Utility\GitCommands
        arguments:
            - @security.token_storage
            - @version_control.project_environmnent_storage
     
    version_control.ssh_process:
        class: VersionContol\GitControlBundle\Utility\SshProcess
     
            
    lrotherfield.form.type.hidden_entity:
        class: Lrotherfield\Component\Form\Type\HiddenEntityType
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: hidden_entity }
            
    version_control.subscriberACL:
        class: VersionContol\GitControlBundle\EventListener\ProjectAccessControlList
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_subscriber }

    version_control.form.registration:
        class: VersionContol\GitControlBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: version_control_user_registration }
            
    salavert.twig.time_ago:
        class: Salavert\Twig\Extension\TimeAgoExtension
        arguments: [@translator]
        tags:
        - { name: twig.extension }
        
    version_control.twig.versioncontrol_textcolor:
        class: VersionContol\GitControlBundle\Twig\Extension\TextColorExtension
        tags:
            - { name: twig.extension }
            
    version_control.project_environmnent_storage:
        class: VersionContol\GitControlBundle\Utility\ProjectEnvironmentStorage
        arguments:
            - @session
            - @doctrine.orm.entity_manager
            
    version_control.twig.versioncontrol_project_environmnent_storage:
        class: VersionContol\GitControlBundle\Twig\Extension\ProjectEnvironmnentStorageExtension
        tags:
            - { name: twig.extension }
        arguments:
            - @version_control.project_environmnent_storage
            
    version_control.twig.versioncontrol_parentdirectory:
        class: VersionContol\GitControlBundle\Twig\Extension\ParentDirectoryExtension
        tags:
            - { name: twig.extension }        
           
    version_control.beforecontoller.action_listener:
        class: VersionContol\GitControlBundle\EventListener\ProjectEnviromentBeforeListener
        arguments: 
            - @version_control.project_environmnent_storage
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            
    version_control.validator.ssh_details_validator:
        class: VersionContol\GitControlBundle\Validator\Constraints\SshDetailsValidator
        tags:
            - { name: validator.constraint_validator, alias: ssh_details_validator }
        arguments: 
            - @version_control.ssh_process
            
    version_control.api_user_provider:
        class: VersionContol\GitControlBundle\Security\Authentication\FOSVersionUserProvider
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: 
            - @fos_user.user_manager
            - {github:githubId}
            