    
services:
   
    version_control.git_commands:
        class: VersionContol\GitControlBundle\Utility\GitCommands\GitCommand
        calls:
            - [setSecurityContext, ["@security.token_storage"]]
            - [setProjectEnvironmentStorage, ["@version_control.project_environmnent_storage"]]
            - [setDispatcher, ["@event_dispatcher"]]
            - [setLogger, ["@version_control.logger"]]
            - [setSshProcess, ["@version_control.ssh_process"]]       
            
              
    version_control.gitcommand_collector:
        class: VersionContol\GitControlBundle\Profiler\GitCommandCollector
        tags:
            -
                name:     data_collector
                template: 'VersionContolGitControlBundle:Profiler:GitCommand.html.twig'
                id:       'version_control.gitcommand_collector'
                #priority: 300
        public: false
        arguments:
            - @version_control.logger
        
    version_control.logger:  
        class: VersionContol\GitControlBundle\Logger\GitCommandLogger
        arguments:
            - @logger
            - %kernel.debug%
        tags:
            - { name: monolog.logger, channel: 'gitcommand' }  
       
    version_control.issue_repository_manager:
        class:  VersionContol\GitControlBundle\Repository\Issues\IssueRepositoryManager
        arguments:
            - @security.token_storage
            - @doctrine.orm.entity_manager
            - @service_container
        