    
services:
    version_control.ssh_process:
        class: VersionControl\GitCommandBundle\Service\SshProcess
        
    version_control.git_commands:
        class: VersionControl\GitCommandBundle\GitCommands\GitCommand
        calls:
            - [setSecurityContext, ["@security.token_storage"]]
            - [setDispatcher, ["@event_dispatcher"]]
            - [setLogger, ["@version_control.logger"]]
            - [setSshProcess, ["@version_control.ssh_process"]]       
            
    version_control.gitcommand_collector:
        class: VersionControl\GitCommandBundle\Profiler\GitCommandCollector
        tags:
            -
                name:     data_collector
                template: 'VersionControlGitCommandBundle:Profiler:GitCommand.html.twig'
                id:       'version_control.gitcommand_collector'
                #priority: 300
        public: false
        arguments:
            - @version_control.logger          
            
        
    version_control.logger:  
        class: VersionControl\GitCommandBundle\Logger\GitCommandLogger
        arguments:
            - @logger
            - %kernel.debug%
        tags:
            - { name: monolog.logger, channel: 'gitcommand' }  
       
